"""Electronics Category Taxonomy and aliases for TrustLens."""

from typing import Any

# Canonical category taxonomy
ELECTRONICS_TAXONOMY: dict[str, dict[str, Any]] = {
    "Smartphones": {
        "subcategories": [
            "iPhone",
            "Samsung",
            "OnePlus",
            "Google Pixel",
            "Xiaomi",
            "Other",
        ],
        "aliases": [
            "mobile",
            "phone",
            "cellphone",
            "smartphone",
            "smartphones",
            "mobiles",
            "cell phones",
            "handset",
        ],
    },
    "Gaming": {
        "subcategories": [
            "PlayStation",
            "Xbox",
            "Nintendo Switch",
            "GPU",
            "Gaming PC",
        ],
        "aliases": [
            "gaming",
            "video games",
            "console",
            "consoles",
            "graphics card",
            "gpu",
            "playstation",
            "ps4",
            "ps5",
            "xbox",
            "nintendo",
        ],
    },
    "Cameras": {
        "subcategories": [
            "DSLR",
            "Mirrorless",
            "Lens",
            "Action Camera",
        ],
        "aliases": [
            "camera",
            "cameras",
            "dslr",
            "mirrorless",
            "photography",
            "cam",
            "lenses",
            "action camera",
            "gopro",
        ],
    },
    "Laptops": {
        "subcategories": [
            "MacBook",
            "Windows Laptop",
            "Gaming Laptop",
        ],
        "aliases": [
            "laptop",
            "laptops",
            "notebook",
            "notebooks",
            "macbook",
            "computer",
            "pc",
            "ultrabook",
        ],
    },
    "Audio & Wearables": {
        "subcategories": [
            "AirPods",
            "Headphones",
            "Earbuds",
            "Smartwatch",
        ],
        "aliases": [
            "audio",
            "wearables",
            "airpods",
            "headphones",
            "earbuds",
            "headset",
            "earphones",
            "tws",
            "smartwatch",
            "watch",
            "fitness band",
        ],
    },
}

SUBCATEGORY_ALIASES: dict[str, tuple[str, str]] = {
    # (canonical_category, canonical_subcategory)
    "iphone": ("Smartphones", "iPhone"),
    "apple iphone": ("Smartphones", "iPhone"),
    "samsung galaxy": ("Smartphones", "Samsung"),
    "samsung": ("Smartphones", "Samsung"),
    "oneplus": ("Smartphones", "OnePlus"),
    "pixel": ("Smartphones", "Google Pixel"),
    "google pixel": ("Smartphones", "Google Pixel"),
    "xiaomi": ("Smartphones", "Xiaomi"),
    "redmi": ("Smartphones", "Xiaomi"),
    "mi": ("Smartphones", "Xiaomi"),
    "ps5": ("Gaming", "PlayStation"),
    "playstation 5": ("Gaming", "PlayStation"),
    "ps4": ("Gaming", "PlayStation"),
    "playstation 4": ("Gaming", "PlayStation"),
    "xbox series x": ("Gaming", "Xbox"),
    "xbox series s": ("Gaming", "Xbox"),
    "xbox one": ("Gaming", "Xbox"),
    "xbox": ("Gaming", "Xbox"),
    "nintendo switch": ("Gaming", "Nintendo Switch"),
    "switch": ("Gaming", "Nintendo Switch"),
    "graphics card": ("Gaming", "GPU"),
    "gpu": ("Gaming", "GPU"),
    "rtx": ("Gaming", "GPU"),
    "gtx": ("Gaming", "GPU"),
    "gaming pc": ("Gaming", "Gaming PC"),
    "macbook": ("Laptops", "MacBook"),
    "macbook pro": ("Laptops", "MacBook"),
    "macbook air": ("Laptops", "MacBook"),
    "windows laptop": ("Laptops", "Windows Laptop"),
    "gaming laptop": ("Laptops", "Gaming Laptop"),
    "dslr": ("Cameras", "DSLR"),
    "mirrorless": ("Cameras", "Mirrorless"),
    "camera lens": ("Cameras", "Lens"),
    "lens": ("Cameras", "Lens"),
    "action camera": ("Cameras", "Action Camera"),
    "gopro": ("Cameras", "Action Camera"),
    "airpods": ("Audio & Wearables", "AirPods"),
    "airpods pro": ("Audio & Wearables", "AirPods"),
    "headphones": ("Audio & Wearables", "Headphones"),
    "earbuds": ("Audio & Wearables", "Earbuds"),
    "smartwatch": ("Audio & Wearables", "Smartwatch"),
    "apple watch": ("Audio & Wearables", "Smartwatch"),
}
